name: run-tests

on:
  push:
    branches:
      - main
      - full-dicos
  workflow_dispatch:

jobs:
  build:
    name: Run tests and coverage upload
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      DISPLAY: ':99.0'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils freeglut3-dev xvfb x11-utils
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock pytest-qt pytest-xvfb

    - name: Run tests
      run: |
        sudo xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1920x1200x24 -ac +extension GLX" pytest --cov-report=xml --cov=ctviewer tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.5.0
      with:
        files: ./coverage.xml
        env_vars: inputs.os, inputs.python-version
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true